name: Build

on:
    workflow_dispatch:
        inputs:
            ref:
                description: 'The branch or tag to build'
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    build:
        uses: nordicsemi/pc-nrfconnect-shared/.github/workflows/build-app.yml@main
        with:
            ref: ${{ inputs.ref }}
